name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main

env:
  AWS_REGION: eu-west-1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Package application
      run: |
        zip -r application.zip .

    - name: Deploy to Elastic Beanstalk
      uses: aws-actions/aws-cli@v1
      with:
        args: aws elasticbeanstalk create-application-version --application-name teststatic --version-label Sample Application-1 --source-bundle S3Bucket=myawscompartimentwinnie,S3Key=application.zip
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
